// public class QuestParameters
// {


// Login()
// {
//     Dashboard()
//     {
//         Settings()
//         {

//         }
//         Friends()
//         {

//         }
//         CharacterSelect()
//         {

//         }
//         StartQuest()
//         {
//             Lobby()
//             {
//                 Invite()
//                 {

//                 }
//                 Quest()
//                 {
//                     QuestDetails()
//                     {
//                         Name()
//                         Difficulty()
//                         Time()
//                         PlayerCount()
//                         TurnOrder()
//                         FactionOne()
//                         FactionTwo()
//                         Theme()
//                     }
//                     CharacterMenus()
//                     {
//                         Challenges()
//                         {

//                         }
//                         Skills()
//                         {
//                             Categories()
//                             {
//                                 Name()
//                                 Quads()
//                                 {
//                                     Name()
//                                     LVL()
//                                     Effect()
//                                     Skills()
//                                     {
//                                         Name()
//                                         LVL()
//                                         Effect()
//                                         Node()
//                                     }
//                                 }
//                             }
//                         }
//                         Pack()
//                         {
//                             Inventory()
//                             {
//                                 Items()
//                                 {
//                                     ItemDetails()
//                                 }
//                             }
//                             Holsters()
//                             {
//                                 Items()
//                                 {
//                                     ItemDetails()
//                                 }
//                             }
//                             Armor()
//                             {
//                                 Items()
//                                 {
//                                     ItemDetails()
//                                 }
//                             }
//                         }
//                         Avatar()
//                         {
//                             Image()
//                             LVL()
//                             EXP()
//                             Settings()
//                             Zoom()
//                         }
//                         HotSwaps()
//                         {
//                             Details()
//                             Actions()
//                         }
//                     }
//                     CharacterData()
//                     {
//                         Health()
//                         Armor()
//                         Standard()
//                         Movement()
//                     }
//                     Objectives()

//                     Map()
//                     {
//                         Viewport()
//                         {
//                             Zones()
//                             {
//                                 ZoneActions()
//                                 {
//                                     BuffTile()
//                                     DebuffTile()
//                                 }
//                                 Teleport()
//                                 {
//                                     Teleporter()
//                                     UseTeleport()
//                                 }
//                                 Spawn()
//                                 {
//                                     Spawner()
//                                     AttackSpawner()
//                                 }
//                                 ActorLists()
//                                 {
//                                     Friendlies()
//                                     {

//                                     }
//                                     Foes()
//                                     {

//                                     }
//                                 }
//                                 Loot()
//                                 {
//                                     Pack()
//                                     {

//                                     }
//                                     Chest()
//                                     {

//                                     }

//                                 }
//                                 Trap()
//                                 {

//                                 }
//                                 Objectives()
//                                 {
//                                     DoTask()
//                                 }
//                             }
//                         }
//                     }
//                 }
//             }
//         }
//     }
// }




// }




// Zone()
// {
//     ActionBins()
//     {
//         Names()
//         RepresentativeGraphics()
//         {
//             Avatars()
//             UI()
//         }
//         MouseEvents()
//         {
//             Hover()
//             MouseUpDown()
//         }
//         Actions()
//         {
//             LargePopovers()
//             SmallPopovers()
//         }
//     }
//     WallBins()
//     {
//         HasWallInDirection()
//         WallTypes()
//         {
//             Open()
//             {
//                 Bare()
//                 Broken()
//                 Decorative()
//             }
//             Solid()
//             {
//                 Wooden()
//                 Metalic()
//                 Block()
//                 Reinforced()
//                 Leaden()
//             }
//             Doorway()
//             {
//                 Normal()
//                 {
//                     Locked()
//                     {
//                         Pick()
//                         Smash()
//                         UseKey()
//                     }
//                     Unlocked()
//                     {
//                         Open()
//                         Shut()
//                         Lock()
//                         Smash()
//                     }
//                     Jammed()
//                     {
//                         Smash()
//                         Unjam()
//                     }
//                     Barricade()
//                     {
//                         Smash()
//                         Reenforce()
//                     }
//                     Broken()
//                     {
//                         Barricade()
//                         Repair()
//                     }
//                 }
//                 Security()
//                 {
//                     Barred()
//                     {
//                         Explode()
//                         UsePasscode()
//                     }
//                     Scanner()
//                     {
//                         Hack()
//                         UseKeyCard()
//                     }
//                     Vault()
//                     {
//                         Explode()
//                         Hack()
//                         UseCombination()
//                     }
//                 }
//             }
//         }
//     }
// }